# Generated by Django 4.2.13 on 2025-04-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug", name="created_at", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="bug", name="modified_count", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bug", name="priority", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bug", name="status", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bug", name="updated_at", field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="BugModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_modified", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("modified_at", models.DateTimeField()),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="issues.bug",
                    ),
                ),
            ],
        ),
    ]
