# Generated by Django 4.2.13 on 2025-04-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_alter_bug_created_at_alter_bug_modified_count_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="BugModification",),
    ]
